# Generated by Django 3.1.7 on 2021-03-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='payment_type',
            field=models.TextField(default='this is cool'),
        ),
    ]
